import { GoldenDatasetLoader } from './testing-framework/src/utils/golden-dataset.js';
import { SummaryEvaluator } from './testing-framework/src/evaluators/summary-evaluator.js';

const loader = new GoldenDatasetLoader();
const evaluator = new SummaryEvaluator();

// The actual summary generated by the LLM
const generatedSummary = `Here is a summary of the call transcript:

The customer called to report being locked out of their account due to a forgotten password and an invalid reset link. The agent assisted by verifying the customer's email address, which had a slight discrepancy, and updated it accordingly. A new password reset link was sent to the corrected email address, and the issue was resolved. The customer reported that this was related to a recent email address change.

Key points:

1. Customer was locked out of their account due to a forgotten password.
2. The agent verified the customer's email address and updated it to resolve the issue.
3. A new password reset link was sent to the corrected email address.

Action items: None`;

const testCase = loader.loadTestCase('call_001');
const result = evaluator.evaluate(generatedSummary, testCase);

console.log('================================');
console.log('QUALITY EVALUATION REPORT');
console.log('================================\n');
console.log(`Test Case: ${testCase.id} (${testCase.category})`);
console.log(`Status: ${result.passed ? '✅ PASSED' : '❌ FAILED'}\n`);
console.log('Metrics:');
console.log(`  Similarity:  ${result.similarity.toFixed(3)} (threshold: ${testCase.thresholds.min_semantic_similarity})`);
console.log(`  BLEU Score:  ${result.bleu.toFixed(3)}`);
console.log(`  Word Count:  ${result.lengthCheck.wordCount} (range: [${testCase.thresholds.min_length_words}, ${testCase.thresholds.max_length_words}])`);
console.log(`  Length Check: ${result.lengthCheck.passed ? '✅ PASS' : '❌ FAIL'}`);
console.log(`  Required Terms Coverage: ${(result.requiredTerms.coverage * 100).toFixed(0)}% (${result.requiredTerms.passed ? '✅ PASS' : '❌ FAIL'})`);

if (result.requiredTerms.missing.length > 0) {
  console.log(`  Missing Terms: ${result.requiredTerms.missing.join(', ')}`);
}

if (result.failures.length > 0) {
  console.log('\nFailures:');
  result.failures.forEach((f, i) => {
    console.log(`  ${i + 1}. ${f}`);
  });
} else {
  console.log('\n✅ All quality checks passed!');
}

console.log('\n================================');
console.log('DETAILED REPORT');
console.log('================================\n');
console.log(evaluator.generateReport(generatedSummary, testCase));
